model_types:
  - id: brunette
    name: Брюнетка
    prompt: "A brunette woman model"
  - id: blonde
    name: Блондинка
    prompt: "A blonde woman model"
  - id: redhead
    name: Шатенка
    prompt: "A redhead woman model"